# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'render_yaml_to_directory',
]

__config__ = pulumi.Config('k3os')

render_yaml_to_directory = __config__.get('renderYamlToDirectory')
"""
directory to render Yaml config
"""

