// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// directory to render Yaml config
func GetRenderYamlToDirectory(ctx *pulumi.Context) string {
	return config.Get(ctx, "k3os:renderYamlToDirectory")
}
