// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface CloudInitFilesArgs {
    content?: pulumi.Input<string>;
    encoding?: pulumi.Input<string>;
    owner?: pulumi.Input<string>;
    path?: pulumi.Input<string>;
    rawFilePermissions?: pulumi.Input<string>;
}

export interface ConnectionArgs {
    addr?: pulumi.Input<string>;
    key?: pulumi.Input<string>;
    user?: pulumi.Input<string>;
}

export interface K3OSArgs {
    environment?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    k3sArgs?: pulumi.Input<pulumi.Input<string>[]>;
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    password?: pulumi.Input<string>;
    serverUrl?: pulumi.Input<string>;
    taints?: pulumi.Input<pulumi.Input<string>[]>;
    token?: pulumi.Input<string>;
}

export interface NodeConfigurationArgs {
    bootCmd?: pulumi.Input<pulumi.Input<string>[]>;
    datasources?: pulumi.Input<pulumi.Input<string>[]>;
    hostname?: pulumi.Input<string>;
    initCmd?: pulumi.Input<pulumi.Input<string>[]>;
    k3OS?: pulumi.Input<inputs.K3OSArgs>;
    modules?: pulumi.Input<pulumi.Input<string>[]>;
    runCmd?: pulumi.Input<pulumi.Input<string>[]>;
    sshAuthorizerKeys?: pulumi.Input<pulumi.Input<string>[]>;
    sysctls?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    writeFiles?: pulumi.Input<inputs.CloudInitFilesArgs>;
}
